# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9JZG-0svZLNWm-WEfCuu1Z6tjYSFoyD
"""

import streamlit as st
import joblib
import numpy as np

# Load trained model
model = joblib.load("model.pkl")

# Species mapping
species_names = {
    0: "Iris Setosa",
    1: "Iris Versicolor",
    2: "Iris Virginica"
}

st.set_page_config(
    page_title="Iris Flower Classifier",
    page_icon="🌸"
)

st.title("🌸 Iris Flower Classification App")

st.write(
    "Enter flower measurements and predict the species."
)

# User Inputs
sepal_length = st.slider(
    "Sepal Length (cm)",
    4.0, 8.0, 5.8
)

sepal_width = st.slider(
    "Sepal Width (cm)",
    2.0, 5.0, 3.0
)

petal_length = st.slider(
    "Petal Length (cm)",
    1.0, 7.0, 4.3
)

petal_width = st.slider(
    "Petal Width (cm)",
    0.1, 3.0, 1.3
)

if st.button("Predict Species"):

    input_data = np.array([
        [
            sepal_length,
            sepal_width,
            petal_length,
            petal_width
        ]
    ])

    prediction = model.predict(input_data)

    st.success(
        f"Predicted Species: {species_names[prediction[0]]}"

    )