# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mnYD0ZB0h9BGUN7R7dr6j5Bq6Hq0uTG

streamlit
pandas
numpy
scikit-learn
joblib
"""